---
- name: Configure a Web Server
  hosts: ubuntuserver
  tasks:
    - name: Update the package manager cache
      apt:
        update_cache: yes
    
    - name: Install the Apache web server package (`apache2`)
      apt:
        name: apache2
        state: present
    
    - name: Enable and start the Apache service
        service:
          name: apache2
          state: started
          enable: yes

    - name:  Deploy a simple `index.html` file   
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome</title>
          </head>
          <body>
              <h1>Hello, Ansible!</h1>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'
        